#!/usr/bin/env python
import subprocess
import os
import requests
import csv

# Grist API key to push the resulting CSV
API_KEY = os.environ["API_KEY"]
# Grist document to push the resulting CSV
DOC_ID = os.environ["DOC_ID"]
# Grist table to push the resulting CSV
TABLE_NAME = os.environ["TABLE_NAME"]
# Path of the CSV file generated by `scripts/<some script>.bash` that should be pushed to Grist
CSV_FILE_PATH = os.environ["CSV_FILE_PATH"]
# Name of the fields in the resulting CSV. They should be the same in the CSV file and in the Grist table
REQUIRE_FIELD = os.environ["REQUIRE_FIELD"]
# Grist instance URL
INSTANCE_URL = os.environ["INSTANCE_URL"]
# Minio Client alias used for running the iterator against
MC_ALIAS_NAME = os.environ.get("MC_ALIAS_NAME", "default")
# S3 bucket used for running the iterator against
S3_BUCKET_NAME = os.environ["S3_BUCKET_NAME"]
# Script name to run on each document, e.g. integrity.bash
SCRIPT_NAME = os.environ["SCRIPT_NAME"]

try:
    run = subprocess.run(f"bash doc-iterator.sh -v {MC_ALIAS_NAME}/{S3_BUCKET_NAME}/docs ./{SCRIPT_NAME}", shell=True)
    run.check_returncode()
except subprocess.CalledProcessError as e:
    print(e)
    print(run.stderr)
    exit(1)


with open(CSV_FILE_PATH, "r") as f:
    reader = csv.DictReader(f, dialect="unix")
    data = list(reader)

headers = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}

# Endpoint URL for updating the table
url = f"{INSTANCE_URL}/api/docs/{DOC_ID}/tables/{TABLE_NAME}/records"

# Upload new data from the CSV
grist_data = {
    "records": [
        {"fields": record, "require": {REQUIRE_FIELD: record[REQUIRE_FIELD]}}
        for record in data
    ]
}
response = requests.put(url, headers=headers, json=grist_data)

# Validate the response
if response.status_code != 200:
    print("Failed to upload data")
    print(response.text)
else:
    print("Data uploaded successfully!")
